### ISSUE TITLE
How can I apply this smooth scroll to a container?

### ISSUE THREAD

**Issue by adrubio** [cferdinandi/smooth-scroll#398] opened 2017-11-20 00:19 UTC
Instead smooth scrolling the whole page, I need to smooth scroll in a container like this

![container](https://user-images.githubusercontent.com/25162531/32997480-9457dec0-cd45-11e7-8715-8a702b0ca07e.PNG)

I've already tried this but it won't work
https://github.com/cferdinandi/smooth-scroll/pull/291

Do am I missing any step or setting?

I really like this plug-in, I will appreciate any help. Thanks!

**Comment by cferdinandi** [comment] 2017-11-20 03:13
Not supported. Duplicate of https://github.com/cferdinandi/smooth-scroll/issues/173.

**Closed by cferdinandi** 2017-11-20 03:13 UTC
