### ISSUE TITLE
Setting tabindex in stopAnimateScroll causes unwanted jump after scroll

### ISSUE THREAD

**Issue by tu4mo** [cferdinandi/smooth-scroll#281] opened 2016-09-02 18:15 UTC
Here's a [Fiddle](https://jsfiddle.net/tu4mo/b3qvg3th/) to demonstrate the issue. I'm using Chrome 52 on OS X 10.11.6.

**Comment by cferdinandi** [comment] 2016-09-02 18:18
Interesting bug! Let me do a bit of research on this and get it fixed.

**Comment by cferdinandi** [comment] 2016-09-04 02:44
I've found the cause: default browser behavior is to jump to an element when it comes into focus. We need to bring the anchored element into focus for accessibility reasons, but the jump can be prevented by jumping back to our end location after focus:

```js
root.scrollTo( 0 , endLocation );
```

I'll be adding this to a future release, sometime in the next few days.

**Comment by cferdinandi** [comment] 2016-09-04 17:59
This is fixed with v9.4.3: https://github.com/cferdinandi/smooth-scroll/releases/tag/v9.4.3

I'm about to issue a breaking version (v10.x) as well, which also contains this fix but implements a new approach.

**Closed by cferdinandi** 2016-09-04 17:59 UTC
Labels: bug

**Comment by tu4mo** [comment] 2016-09-05 18:58
Thanks for the fix!

**Comment by cferdinandi** [comment] 2016-09-05 19:14
No problem. Thanks for letting me know about it!
