### ISSUE TITLE
Selector bug

### ISSUE THREAD

**Issue by Twikito** [cferdinandi/smooth-scroll#267] opened 2016-08-02 21:32 UTC
Hi,

I tried to initiate smoothScroll like this:
```js
smoothScroll.init({ selector: 'a[href^="#"]' });
```
but it doesn't seems to work. Any idea?

**Comment by cferdinandi** [comment] 2016-08-05 14:23
It's not a bug so much as some poorly written documentation and a side effect of how the script works.

Any time there's a click, the script evaluates it to see if the clicked item contains the class, ID, tag type, or data selector passed in my the `selector` attribute. As a result, something like `selector: 'a'` works, but `selector: 'a[href="#"]'` does not. There's no good cross-browser way around this that doesn't add a bunch more complexity to the script.

To programmatically target all anchor links, I [recommend using this approach](https://github.com/cferdinandi/smooth-scroll#programatically-adding-data-scroll-attributes-to-all-anchor-links).

I'm going to leave this open though as a reminder to update the documentation to make this more clear. Thanks!

**Comment by Twikito** [comment] 2016-08-05 14:51
Thanks for this answer.

Ok, I understand.
In fact, your solution is exactly what I've done: add the ``data-scroll`` attribute on each links which have an ``href`` that begins by ``#``, but I though that was a step that could be avoided by passing this selector in your ``selector`` parameter.

According to [Can I Use](http://caniuse.com/#feat=css-sel3), it seems that the selector ``[attr^=val]`` works on IE7 and IE8. Don't you think this option could be useful?

**Comment by cferdinandi** [comment] 2016-08-05 15:00
Oh, it's not that the attribute selectors wouldn't work. It's that the way the script is written with event bubbling, I need to check if the clicked element contains the selector (vs just adding click events to every selector that matches—better for performance), and checking against that type of selector is way more complicated.

It can definitely be done, but it requires a lot more code. Here's what I'm mean...

First, I listen for any click on the page: https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L495

Then, I check to see if the clicked element matches the selector: https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L425-L438

Since the selector can be a class, ID, or data attribute, I need to figure out what type of selector it is first: https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L92-L162

That last part is already a bit cumbersome, and allowing for attribute selectors further complicates it. That said, Remy Sharp (of JSBin fame) just [submitted an awesome PR](https://github.com/cferdinandi/smooth-scroll/pull/266) that checks if the link points externally before preventing the default and animating the scroll.

This will let you simply set do this: `selector: 'a'`, and if the link isn't an anchor, it will just behave as normal. I should be pulling that in soon.

**Comment by cferdinandi** [comment] 2016-08-07 02:03
This has been addressed in v9.2.0, and the docs have been updated accordingly. Thanks again!

https://github.com/cferdinandi/smooth-scroll/releases/tag/v9.2.0

**Closed by cferdinandi** 2016-08-07 02:03 UTC
Labels: bug
