### ISSUE TITLE
Jittery on Mobile

### ISSUE THREAD

**Issue by jcbbuller** [cferdinandi/smooth-scroll#485] opened 2019-09-08 20:50 UTC
I'm having issues where the scroll is jittery on my mobile device. Do you have similar issues? If so, got a solution? Love the plugin though—works great on desktop.

**Comment by cferdinandi** [comment] 2019-09-08 22:15
On the demo too, or your specific implementation? What device/browser. There’s a few things this could be.

**Comment by jcbbuller** [comment] 2019-09-09 02:27
It's on my own project. I put in a javascript filter to deactivate it on mobile and keep it activate on desktop. It gets the job done, but it would be nice if it worked on both.

**Comment by cferdinandi** [comment] 2019-09-09 03:23
I've seen this happen before. The cause is usually a third-party script not debouncing their scroll events. I'm assuming you're using some other scripts on the page, too.

Modern desktop browsers "debounce" scroll events so that they don't fire too frequently when scrolling quickly down a page. This prevents jank. Many mobile browsers, esp on slightly older devices, don't.

Smooth scroll, by the very nature of scrolling down the page, triggers scroll events.

If a third party script hasn't added debouncing for scroll events, the event callbacks try to fire thousands of times a second and bog down the entire UI.

Since the demo doesn't have the problem and I can't provide support for third-party scripts, I'm closing this one. Sorry!

**Closed by cferdinandi** 2019-09-09 03:23 UTC

**Comment by jcbbuller** [comment] 2019-09-10 00:45
Sounds good! I deactivated all the scripts besides standard jQuery and SmoothScroll.js and it is still being jittery. I'm using an Iphone8 X with Chrome. Again, detecting whether or not you're viewing the site on a mobile device then activating/deactivating it accordingly is a good workaround. Appreciate the help! 

For anyone else who might be having this issue, this is what I added to the end to deactivate it on mobile. 

var isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
		if (isMobile) {
		} else {
      new SmoothScroll('.smooth', params)
		}
