### ISSUE TITLE
Getting console error message on init 'Uncaught TypeError: o.default is not a constructor'

### ISSUE THREAD

**Issue by dayneh88** [cferdinandi/smooth-scroll#366] opened 2017-07-24 06:45 UTC
Hi Chris,
First of all, love the package! I'm using yarn to manage my packages and I've managed to add it correctly. Import is in ES6 by having `import SmoothScroll from 'smooth-scroll'` at the top of my component. When I `console.log(SmoothScroll);` it appears in my console. All working fine!

The moment I run my init `var scroll = new SmoothScroll('a[href*="#"]');` I get the following error in my console.

`Uncaught TypeError: o.default is not a constructor
    at new e (index.js:17)
    at index.js:23
    at Array.forEach (<anonymous>)
    at index.js:22
`
Any ideas as to why this is happening? Wasn't happening on older versions of your smooth scroll.

Cheers,
Dayne

**Comment by wereHamster** [comment] 2017-07-25 05:33
I ran into two similar problems in a webpack project:

1. When I import `smooth-scroll` and try to use the constructor function it throws an exception. Could be a problem caused by webpack.

> Uncaught TypeError: Cannot use 'in' operator to search for 'addEventListener' in undefined

2. When I import the source file directly instead of the precompiled/minified library (for easier debugging), I get an instance instead of a constructor function. Could be caused by webpack, too FWIW.

My guess is that the UMD prelude isn't compatible with webpack and webpack messes something up while transforming it.

My code looks now (you can probably replace `require` with `import` if you use ES6 modules):

```javascript
var scroll = require('smooth-scroll/dist/js/smooth-scroll')

exports.smoothScrollTo = function(selector) {
  var anchor = document.querySelector(selector)
  scroll.animateScroll(anchor)
}
```

**Comment by cferdinandi** [comment] 2017-07-29 13:48
It is also possible that I messed up my UMD header. I recently swapped out references to `root` with `window`, and I wonder if that's breaking things.

Do either of you have a reduced test case I can look at to help me debug?

As far as I know, Webpack and UMD should play nice together (that's literally the whole point of UMD_

**Comment by cferdinandi** [comment] 2017-08-01 23:54
@dayneh88 @wereHamster Can either you of you pull the latest version (12.1.1: https://github.com/cferdinandi/smooth-scroll/pull/368) and tell me if this issue persists? I switched `window` to `root` in the UMD header, hoping that addresses the issue.

**Comment by dayneh88** [comment] 2017-08-02 02:35
Hi Chris,
I've done a pull and updated to v12.1.1.
I'm still getting the error message:
`Uncaught TypeError: d.default is not a constructor
    at new e (index.js:18)
    at index.js:24
    at Array.forEach (<anonymous>)
    at index.js:23`

This is what I have in my global header component's JS file.
`import Headroom from 'headroom.js'
import SmoothScroll from 'smooth-scroll'

/**
 * Global Header functionality.
 * @author Dayne Coulson-Hoffacker
 */
export default class GlobalHeader {
  /**
   * Constructs a new Global Header instance.
   * @param {Object} options - Options.
   * @param {HTMLElement} options.element - Container.
   */
  constructor (options) {
    this.element = options.element
    var scroll = new SmoothScroll()
  }
}
`
If I run a console log on SmoothScroll is gives my the correct output. The moment I add `var scroll = new SmoothScroll()` I get the error message above.

**Comment by cferdinandi** [comment] 2017-08-02 03:29
Do you have a demo link I can view? CodePen or JSFiddle or something?

**Comment by tilarm** [comment] 2017-08-02 09:41
Hello, I hope I can help
Same issue using custom-react-scripts (React + Webpack boilerplate).

Example with Webpack only :
https://www.webpackbin.com/bins/-KqXDK5GeW765WFqqr04

**Comment by cferdinandi** [comment] 2017-08-02 12:03
Hmm... looks like WebPack is getting an object instead of the function constructor. I don't use module bundlers, so it's unclear to me what's happening here.

I'm going to see if I can get some additional eyes on this to figure out what's going on. Not sure if it's an issue with instantiation or my UMD header, but we'll get this sorted out!

**Comment by cferdinandi** [comment] 2017-08-03 17:00
This should now be fixed with https://github.com/cferdinandi/smooth-scroll/pull/370. Can anyone confirm?

**Comment by cferdinandi** [comment] 2017-08-03 17:34
Tested, this appears to be fixed: https://www.webpackbin.com/bins/-Kqd86DwcDgR7uYRcRxC

Closing this one out.

**Closed by cferdinandi** 2017-08-03 17:34 UTC
Labels: bug

**Comment by dayneh88** [comment] 2017-08-04 00:02
Yep. All working now. Great work guys. Thanks

**Comment by cferdinandi** [comment] 2017-08-04 00:05
Woohoo! Special thanks to @desandro for identifying the issue and PRing the fix.
