### ISSUE TITLE
Does not support Chinese anchor well in Safari

### ISSUE THREAD

**Issue by Jinjiang** [cferdinandi/smooth-scroll#305] opened 2016-12-25 06:04 UTC
demo: http://output.jsbin.com/foziyafiti

In my macOS Safari 10.0.1, it doesn't scroll smoothly.

I find that `document.querySelector('#中文2')` is OK but `document.querySelector('a[href="#中文2"]').hash` returns `"#%E4%B8%AD%E6%96%872"`，and `document.querySelector(document.querySelector('a[href="#中文2"]').hash)` makes an error. Maybe something hacks needed in Safari I guess.

Thanks.

**Comment by cferdinandi** [comment] 2016-12-25 13:50
How strange! Thanks for the demo link - that will be really helpful for debugging. I'll try to get this fixed soon.

**Comment by Alex-Sokolov** [comment] 2016-12-25 17:03
With cyrillic anchors doesn't work too

Example: https://ru.vuejs.org/v2/guide/

**Comment by gbezyuk** [comment] 2016-12-25 21:33
Seems to be relevant for any non-ASCII characters. Reproduced in FF, not reproduced in Chrome (both Mac OS X).

**Comment by cferdinandi** [comment] 2016-12-26 03:16
Some additional clarity here. Chrome outputs the `hash` (and `href`) of non-ASCII characters as their actual characters, while Firefox and Safari (unsure about IE and Edge) render an encoded version.

- Real Characters: `#中文`
- Encoded: `#%E4%B8%AD%E6%96%87`

It looks like this can be fixed by running the characters through `decodeURIComponent()`. [See this fiddle for an example](https://jsfiddle.net/cferdinandi/sswnq45x/4/) (check the console logs).

This issue affects any script using `hash` or `href` with non-ASCII characters, unfortunately. This strikes me as a browser bug, and should likely be reported to the browser vendors. Unless Chrome is deviating from the "correct" behavior on this one.

Thoughts there?

I'll try to push a fix for this soon, but in the name of transparency, I have a few other priorities that will take precedence over this.

**Comment by gbezyuk** [comment] 2016-12-26 09:10
Awesome research, Chris! I guess we all agree on all of you've mentioned above. So, please just let us know when there will be the new fixed version available. It's important, but not too important, however, so please keep your priorities.

**Comment by cferdinandi** [comment] 2016-12-26 13:46
Fixed: https://github.com/cferdinandi/smooth-scroll/pull/307

Working demo: https://jsfiddle.net/cferdinandi/w190zrax/

**Closed by cferdinandi** 2016-12-26 13:46 UTC
Labels: bug
