### ISSUE TITLE
Remove selectorHeader from mobile

### ISSUE THREAD

**Issue by chandanndeep** [cferdinandi/smooth-scroll#315] opened 2017-03-15 22:57 UTC
How I remove the below function from mobile layout
<script> smoothScroll.init({ selectorHeader: '[data-scroll-header]' }); </script>

**Comment by cferdinandi** [comment] 2017-03-15 23:11
Duplicate of https://github.com/cferdinandi/smooth-scroll/issues/314

**Closed by cferdinandi** 2017-03-15 23:11 UTC
